<%@ Control Language="VB" AutoEventWireup="false" CodeFile="ucMenu.ascx.vb" Inherits="ucMenu" %>
<table style="margin-top:0" width="100%" ><tr><td>
<TD valign="top">
<DIV webpartid="00000000-0000-0000-0000-000000000000" haspers="true" id="WebPartWPQ2" width="100%" onlyformepart="true" allowdelete="false" style="">
<DIV class="PortalMainMenuInActive" onmouseover="this.className=&#39;PortalMainMenuActive&#39;;" onmouseout="this.className=&#39;PortalMainMenuInActive&#39;;" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"><DIV><DIV><DIV>
<A href="TrangChu.aspx">Trang chủ</A>
</DIV></DIV></DIV></DIV><DIV class="PortalMainMenuDivider" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"></DIV><DIV class="PortalMainMenuInActive" onmouseover="this.className=&#39;PortalMainMenuActive&#39;;" onmouseout="this.className=&#39;PortalMainMenuInActive&#39;;" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"><DIV><DIV><DIV>
<A href="TrangChu.aspx">Tìm kiếm sách</A>
</DIV></DIV></DIV></DIV><DIV class="PortalMainMenuDivider" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"></DIV><DIV class="PortalMainMenuInActive" onmouseover="this.className=&#39;PortalMainMenuActive&#39;;" onmouseout="this.className=&#39;PortalMainMenuInActive&#39;;" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"><DIV><DIV><DIV>
<A href="TinTuc.aspx">Tin tức - Sự kiện</A></DIV></DIV></DIV></DIV><DIV class="PortalMainMenuDivider" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"></DIV><DIV class="PortalMainMenuInActive" onmouseover="this.className=&#39;PortalMainMenuActive&#39;;" onmouseout="this.className=&#39;PortalMainMenuInActive&#39;;" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal"><DIV><DIV><DIV>
<A href="DangNhap.aspx"> Quản trị tin tức </A></DIV></DIV></DIV></DIV><DIV class="PortalMainMenuDivider" xmlns:sharepoint="Microsoft.SharePoint.WebControls" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:ddwrt2="urn:frontpage:internal">
</td></tr></table>