




var gsfx_brnd_surroundingheight=0;var gsfx_brnd_resizeContentArea=function(){var ca=$('#contentArea').get(0);var pc=$('#gsfx_brnd_PageContainer').get(0);if(ca&&pc){if(!gsfx_brnd_surroundingheight){gsfx_brnd_surroundingheight=0;for(var i=0;i<pc.childNodes.length;i++){
 
 if(pc.childNodes[i].nodeType===1&&pc.childNodes[i].id!='gsfx_brnd_ContentContainer'&&pc.childNodes[i].id!='gsfx_brnd_PageHeaderImage'){gsfx_brnd_surroundingheight+=pc.childNodes[i].offsetHeight;}}}var bh=$(window).height();if(bh>gsfx_brnd_surroundingheight){bh=(bh>450)? bh : 450;pc.style.height=bh;ca.style.height=bh - gsfx_brnd_surroundingheight;}}};


var gsfx_brnd_resizetimer=setInterval(gsfx_brnd_resizeContentArea,250);
function gsfx_brnd_CreateLeftNavFlyout(el,doMatte){if(typeof(el)==='string'){el=$('#'+el).get(0);}if(!el){return;}if (/MSIE ([1-6])/.test(navigator.userAgent)){doMatte=true;}var menuItems=el.getElementsByTagName('li');for(var i=0;i<menuItems.length;i++){var hasUL=menuItems[i].getElementsByTagName('UL')[0];if(hasUL){menuItems[i].className+=' gsfx_lnav_upmenu gsfx_lnav_submenu';var mdiv=document.createElement('div');mdiv.className='gsfx_lnav_menulink';var linknode=menuItems[i].getElementsByTagName('a')[0];var linknodechildren=linknode.childNodes;linknode.insertBefore(mdiv,linknodechildren[0]);var mover=function(event){var e=($.browser.msie)? srcEl(event): this;e.className=e.className.replace(/( ?|^)gsfx_lnav_upmenu\b/gi,'gsfx_lnav_dropmenu');gsfx_brnd_MoveFlyout(e);};var mout=function(event){var e=($.browser.msie)? srcEl(event): this;e.className=e.className.replace(/( ?|^)gsfx_lnav_dropmenu\b/gi,'gsfx_lnav_upmenu');};$(menuItems[i]).hover(mover,mout);if(doMatte===true){var ifMatte=document.createElement('IFRAME');ifMatte.className='gsfx_lnav_iframeMatte';ifMatte.style.height=(hasUL.offsetHeight+2)+'px';ifMatte.style.width=(hasUL.offsetWidth+2)+'px';hasUL.insertBefore(ifMatte,hasUL.firstChild);}}else{menuItems[i].className+=' gsfx_lnav_nomenu';}}}$(document).ready(function(){gsfx_brnd_CreateLeftNavFlyout('gsfx_lnav_LeftNav');});


function gsfx_brnd_MoveFlyout(e){var flyout=srcEl(e);if(flyout){var hasUL=flyout.getElementsByTagName('UL')[0];if(hasUL){var fp=AbsPos(flyout);var y=(window.event)? document.documentElement.scrollTop+document.body.scrollTop : window.scrollY;if((fp.top+hasUL.offsetHeight - y)>$(window).height()){hasUL.style.top=-((fp.top+hasUL.offsetHeight)-($(window).height()+y))+'px';}else{hasUL.style.top="0px";}}}}var gsfx_bsrch_InitCatSelection=function(targetid,charstr){var cval=unescape(fetchcookieval('adcatalog'));var a=0;var highlight=false;if(cval){var catcon=$('#gsfx_bsrch_catsel').get(0);if(catcon){for(var i=0;i<catcon.childNodes.length;i++){var el=catcon.childNodes[i];if(el&&el.tagName&&el.getAttribute('catalog')){if(el.getAttribute('catalog')==cval){el.className+=' gsfx_bsrch_highlight';try{MS.Support.AC.ACChangeCharStart(targetid,charstr.split(':')[a]);MS.Support.AC.ACSetLcid(targetid,cval.split('=')[1]);}catch(e){}highlight=true;}else{el.className=el.className.replace(/( ?|^)gsfx_bsrch_highlight\b/gi,'');}a++;}}if(!highlight){for(var i=0;i<catcon.childNodes.length;i++){var el=catcon.childNodes[i];if(el&&el.tagName&&el.getAttribute('catalog')){el.className+=' gsfx_bsrch_highlight';return;}}}}}};var gsfx_brnd_ToolbarSelection=function(){if(!$('#gsfx_brnd_LocalLinks').get(0)){return false;}
 var baseurl=document.location.href;var links=$('#gsfx_brnd_LocalLinks a');var tstr;for(var i=0;i<links.length;i++){tstr=links[i].href
 if(tstr==baseurl){links[i].parentNode.className+=' gsfx_brnd_LocalLinkSelected';return;}}

 baseurl=baseurl.split('?')[0].split('#')[0].replace(/( ?|^)default.aspx\b/gi,'');for(var i=0;i<links.length;i++){tstr=links[i].href.split('?')[0].split('#')[0].replace(/( ?|^)default.aspx\b/gi,'');;if(tstr==baseurl){links[i].parentNode.className+=' gsfx_brnd_LocalLinkSelected';return;}}};$(document).ready(gsfx_brnd_ToolbarSelection);var gsfx_brnd_dontshowad=function(){var d=new Date();var cs='mcUA='+d.toUTCString()+';expires='+d.toGMTString(d.setFullYear(d.getFullYear()+1))+'; Domain=microsoft.com;path=/';document.cookie=cs;};$('#gsfx_brnd_corpflyoutad_go').click(gsfx_brnd_dontshowad);var gsfx_brnd_flyoutad_close=function(perm){$('#gsfx_brnd_corpflyoutad').animate({width: '0px',height: '0px',opacity: 0},750,null,function(){$('#gsfx_brnd_corpflyoutad_inner').css('display','none');if(perm===true){gsfx_brnd_dontshowad();}});};$('#gsfx_brnd_corpflyoutad_close').click(gsfx_brnd_flyoutad_close);var gsfx_brnd_flyoutad_close_perm=function(){gsfx_brnd_flyoutad_close(true);};$('#gsfx_brnd_corpflyoutad_dontshow').click(gsfx_brnd_flyoutad_close_perm);var gsfx_brnd_flyoutad_open=function(autoclose){$('#gsfx_brnd_corpflyoutad_inner').css('display','block');$('#gsfx_brnd_corpflyoutad').animate({width: $('#gsfx_brnd_corpflyoutad_inner').css('width'),height: $('#gsfx_brnd_corpflyoutad_inner').css('height'),opacity: 1},750,function(){$('#gsfx_brnd_corpflyoutad_inner').css('display','block');var d=new Date();var cs='mcI='+d.toUTCString(d.setDate(d.getDate()+7))+';expires='+d.toGMTString(d.setFullYear(d.getFullYear()+1))+'; Domain=microsoft.com;path=/';document.cookie=cs;if(autoclose===true){setTimeout(gsfx_brnd_flyoutad_close,4000);}});};$($('#gsfx_brnd_CorpMarketingSpace a').get(0)).click(gsfx_brnd_flyoutad_open);var gsfx_brnd_adspaceload=function(){if($('#gsfx_brnd_CorpMarketingSpace').children().size()==0)return;$('#gsfx_brnd_corpflyoutad').css({opacity: 0});$('#gsfx_brnd_CorpMarketingSpace a').get(0).href='javascript:void(0);';var hasseen=fetchcookieval('mcI');var nevershow=fetchcookieval('mcUA');var ct1=(hasseen)? new Date(hasseen): null;var ct2=(nevershow)? new Date(nevershow): null;var startdate=(gsfx_brnd_ad_pushstartdate)? new Date(gsfx_brnd_ad_pushstartdate): null;var enddate=(gsfx_brnd_ad_pushenddate)? new Date(gsfx_brnd_ad_pushenddate): null;var curdt=new Date();if(curdt>enddate){return null;}if(ct1<startdate||ct2<startdate){hasseen==null;nevershow==null;}if(!nevershow){if(hasseen){var dt=new Date(hasseen);if(curdt>dt){gsfx_brnd_flyoutad_open(true);}}else{gsfx_brnd_flyoutad_open(true);}}};$(document).ready(gsfx_brnd_adspaceload);